### ISSUE TITLE
WanVideoModelLoader ：Unknown attribute allow_fp16_accumulation

### ISSUE THREAD

**Issue by Elain-eddie** [kijai/ComfyUI-WanVideoWrapper#131]
g

![Image](https://github.com/user-attachments/assets/4d1d4470-27c8-4f2a-800c-a3762612747c)

ot prompt
!!! Exception during processing !!! Unknown attribute allow_fp16_accumulation
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.3\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.3\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.3\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI-aki-v1.3\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 307, in loadmodel
    if hasattr(torch.backends.cuda.matmul, "allow_fp16_accumulation"):
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\backends\cuda\__init__.py", line 124, in __getattr__
    raise AssertionError("Unknown attribute " + name)
AssertionError: Unknown attribute allow_fp16_accumulation

May I ask you how to solve this problem, I have been confused for two days and still not solved

**Comment by kijai** [comment]
Your nodes must not be up to date as that issue was fixed days ago.

**Comment by Elain-eddie** [comment]
> Your nodes must not be up to date as that issue was fixed days ago.

![Image](https://github.com/user-attachments/assets/b44788f7-c834-4dcd-8e2d-a48272faf53a)Sorry, I need to ask you again, I cannot download the history version in the manager, is there any other way?

**Comment by kijai** [comment]
Manager seems to have problems with updating lately, or a delay... 

To manually update you can either remove the node folder and reinstall, or open up terminal in this folder:

custom_nodes\ComfyUI-WanVideoWrapper

and run `git pull`

**Comment by Elain-eddie** [comment]
> Manager seems to have problems with updating lately, or a delay...
> 
> To manually update you can either remove the node folder and reinstall, or open up terminal in this folder:
> 
> custom_nodes\ComfyUI-WanVideoWrapper
> 
> and run `git pull`

![Image](https://github.com/user-attachments/assets/cc0802f6-14cb-4481-b1d8-2241e0b80c52)

Thank you for your patient reply in spite of your busy schedule.

I used the terminal to run git pull in the target folder to achieve the purpose of update, later I still encountered the same error（Unknown attribute allow_fp16_accumulation） when executing the workflow, I would like to ask you again for solutions.

**Comment by Elain-eddie** [comment]
> Manager seems to have problems with updating lately, or a delay...
> 
> To manually update you can either remove the node folder and reinstall, or open up terminal in this folder:
> 
> custom_nodes\ComfyUI-WanVideoWrapper
> 
> and run `git pull`

![Image](https://github.com/user-attachments/assets/d7643107-229d-43a3-891d-5f2bd492322b)

Thank you for your patient reply in spite of your busy schedule.

I used the terminal to run git pull in the target folder to achieve the purpose of update, later I still encountered the same error（Unknown attribute allow_fp16_accumulation） when executing the workflow, I would like to ask you again for solutions.

**Comment by kijai** [comment]
> > Manager seems to have problems with updating lately, or a delay...
> > To manually update you can either remove the node folder and reinstall, or open up terminal in this folder:
> > custom_nodes\ComfyUI-WanVideoWrapper
> > and run `git pull`
> 
> ![Image](https://github.com/user-attachments/assets/d7643107-229d-43a3-891d-5f2bd492322b)
> 
> Thank you for your patient reply in spite of your busy schedule.
> 
> I used the terminal to run git pull in the target folder to achieve the purpose of update, later I still encountered the same error（Unknown attribute allow_fp16_accumulation） when executing the workflow, I would like to ask you again for solutions.

Do you have the fp16_fast selected then? It would error in that case if you don't have the needed pytorch version, but the error should say that in the current version....

**Comment by kijai** [comment]
I don't know how that can be up to date as the current error handling wouldn't allow that:

![Image](https://github.com/user-attachments/assets/35484172-4904-4a36-9e2d-dde013e45952)

Try re-installing to be sure.

**Comment by Elain-eddie** [comment]
> I don't know how that can be up to date as the current error handling wouldn't allow that:
> 
> ![Image](https://github.com/user-attachments/assets/35484172-4904-4a36-9e2d-dde013e45952)
> 
> Try re-installing to be sure.

Thank you very much for your reply.

In base_precision I select fp16_fast or bf16 or whatever, and I get the same error.

I also tried to reinstall the node, but this error still occurs.

Do you mean the pytorch version of the problem?

I'm sorry to bother you for so long！

**Comment by kijai** [comment]
Can you check the nodes.py file in the custom nodes folder to see if that code I showed exists? Because it really sounds it's not up to date... or could you possibly have another copy of the node in different folder and it's loaded instead?

**Comment by sukh48** [comment]
I was able to get past this error for now by commenting out this code in nodes.py

 # if base_precision == "fp16_fast":
        #     if hasattr(torch.backends.cuda.matmul, "allow_fp16_accumulation"):
        #         torch.backends.cuda.matmul.allow_fp16_accumulation = True
        #     else:
        #         raise ValueError("torch.backends.cuda.matmul.allow_fp16_accumulation is not available in this version of torch, requires torch 2.7.0.dev2025 02 26 nightly minimum currently")
        # else:
        #     if hasattr(torch.backends.cuda.matmul, "allow_fp16_accumulation"):
        #         torch.backends.cuda.matmul.allow_fp16_accumulation = False

**Comment by Elain-eddie** [comment]
> Can you check the nodes.py file in the custom nodes folder to see if that code I showed exists? Because it really sounds it's not up to date... or could you possibly have another copy of the node in different folder and it's loaded instead?

I sincerely want to express my gratitude!

I seem to have fixed the allow_fp16_accumulation bug by upgrading the pytorch version (although I rolled back the pytorch version).

But I have encountered a new error (as shown in the picture), I hope you can help me answer it again.

![Image](https://github.com/user-attachments/assets/78a2b14d-8c9d-48db-8666-403cb3c64213)

**Comment by ricklove** [comment]
I got the same error, but fixed it by changing to base precision bf16

**Comment by Webtransformer** [comment]
I have the same error and was not able to fix it.
