### ISSUE TITLE
LongCat error in WanWrapper

### ISSUE THREAD

**Issue by Five-Birds** [kijai/ComfyUI-WanVideoWrapper#1738]
Hej Kijaii,
After the newest ComfyUtI updates, one of my workflow with LongCat Video is broken:

Error during model prediction: Head_adaLN.forward() got an unexpected keyword argument 'e_tr'
  0%|                                                                                   | 0/10 [00:11<?, ?it/s]
Error during sampling: Head_adaLN.forward() got an unexpected keyword argument 'e_tr'
!!! Exception during processing !!! Head_adaLN.forward() got an unexpected keyword argument 'e_tr'
Traceback (most recent call last):
  File "I:\002 - AI-Tools\001 - ComfyUI_Sage_2\ComfyUI-Easy-Install\ComfyUI\execution.py", line 515, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\002 - AI-Tools\001 - ComfyUI_Sage_2\ComfyUI-Easy-Install\ComfyUI\execution.py", line 329, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\002 - AI-Tools\001 - ComfyUI_Sage_2\ComfyUI-Easy-Install\ComfyUI\execution.py", line 303, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "I:\002 - AI-Tools\001 - ComfyUI_Sage_2\ComfyUI-Easy-Install\ComfyUI\execution.py", line 291, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "I:\002 - AI-Tools\001 - ComfyUI_Sage_2\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes_sampler.py", line 3188, in process
    raise e
  File "I:\002 - AI-Tools\001 - ComfyUI_Sage_2\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes_sampler.py", line 3052, in process
    noise_pred, noise_pred_ovi, self.cache_state = predict_with_cfg(
                                                   ^^^^^^^^^^^^^^^^^
  File "I:\002 - AI-Tools\001 - ComfyUI_Sage_2\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes_sampler.py", line 1662, in predict_with_cfg
    raise e
  File "I:\002 - AI-Tools\001 - ComfyUI_Sage_2\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes_sampler.py", line 1531, in predict_with_cfg
    noise_pred_cond, noise_pred_ovi, cache_state_cond = transformer(
                                                        ^^^^^^^^^^^^
  File "I:\002 - AI-Tools\001 - ComfyUI_Sage_2\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\002 - AI-Tools\001 - ComfyUI_Sage_2\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\002 - AI-Tools\001 - ComfyUI_Sage_2\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\modules\model.py", line 3125, in forward
    x = self.head(x, e.to(x.device), temp_length=F,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\002 - AI-Tools\001 - ComfyUI_Sage_2\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\002 - AI-Tools\001 - ComfyUI_Sage_2\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Head_adaLN.forward() got an unexpected keyword argument 'e_tr'

**Comment by kijai** [comment]
Fixed probably.

**Comment by Five-Birds** [comment]
Yes, it works again. Thank you my Hero!

**Comment by Five-Birds** [comment]
Wait…you are Finnish ? I lived and worked one year in Rauma. Kiitos for your work in comfyUI- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -Mehr Bilder, Videos und Blogbeiträge findet ihr unter www.5bp.de. Viel Spaß beim stöbern, euer Dirk von Five-Birds Photography! Gesendet via Outlook von meinem iPhone 11 Pro Max. You can find more pictures, videos and blog posts at www.5bp.de. Have fun browsing, your Dirk from Five-Birds Photography! Sent via Outlook from my iPhone 11 Pro MaxVon: Jukka Seppänen ***@***.***>Gesendet: Dienstag, Dezember 9, 2025 8:10 PMAn: kijai/ComfyUI-WanVideoWrapper ***@***.***>Cc: Five-Birds ***@***.***>; Author ***@***.***>Betreff: Re: [kijai/ComfyUI-WanVideoWrapper] LongCat error in WanWrapper (Issue #1738) kijai left a comment (kijai/ComfyUI-WanVideoWrapper#1738)Fixed probably.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.

**Comment by pxl-pshr** [comment]
@Five-Birds getting the same issue even after updating everything. Any thing in particular you did to get it to work?

**Comment by neskweek** [comment]
Hello all, same here: my cat is very sad. 
Still have the issue.

Workflow: 
[LongCat_v03.json](https://github.com/user-attachments/files/24103604/LongCat_v03.json)

ERROR:


```

got prompt
WARNING: [Errno 2] No such file or directory: '/opt/ia/images/ComfyUI/input/00018-_3704846037_DPM++ 2M.png'
Using accelerate to load and assign model weights to device...
Loading transformer parameters to cuda:0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1310/1310 [00:02<00:00, 541.80it/s]
Using 480 LoRA weight patches for WanVideo model
------- Scheduler info -------
Total timesteps: tensor([1000.0000,  992.8058,  984.3750,  974.3589,  962.2642,  947.3684,  923.0769,  896.7972,  860.7595,  808.2901,  724.8322,  571.4286], device='cuda:0')
Using timesteps: tensor([1000.0000,  992.8058,  984.3750,  974.3589,  962.2642,  947.3684,  923.0769,  896.7972,  860.7595,  808.2901,  724.8322,  571.4286], device='cuda:0')
Using sigmas: tensor([1.0000, 0.9928, 0.9844, 0.9744, 0.9623, 0.9474, 0.9231, 0.8968, 0.8608, 0.8083, 0.7248, 0.5714, 0.0000], device='cuda:0')
------------------------------
sigmas: tensor([1.0000, 0.9928, 0.9844, 0.9744, 0.9623, 0.9474, 0.9231, 0.8968, 0.8608, 0.8083, 0.7248, 0.5714, 0.0000], device='cuda:0')
Input sequence length: 37440
Sampling 93 frames at 832x480 with 12 steps
  0%|                                                                                                                                                                                      | 0/12 [00:00<?, ?it/s]Error during model prediction: Head_adaLN.forward() got an unexpected keyword argument 'e_tr'
  0%|                                                                                                                                                                                      | 0/12 [00:27<?, ?it/s]
Error during sampling: Head_adaLN.forward() got an unexpected keyword argument 'e_tr'
!!! Exception during processing !!! Head_adaLN.forward() got an unexpected keyword argument 'e_tr'
Traceback (most recent call last):
  File "/opt/ia/images/ComfyUI/execution.py", line 515, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ia/images/ComfyUI/execution.py", line 329, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ia/images/ComfyUI/execution.py", line 303, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "/opt/ia/images/ComfyUI/execution.py", line 291, in process_inputs
    result = f(**inputs)
  File "/opt/ia/images/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes_sampler.py", line 3178, in process
    raise e
  File "/opt/ia/images/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes_sampler.py", line 3042, in process
    noise_pred, noise_pred_ovi, self.cache_state = predict_with_cfg(
                                                   ~~~~~~~~~~~~~~~~^
        latent_model_input,
        ^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        wananim_face_pixels=wananim_face_pixels, wananim_pose_latents=wananim_pose_latents, uni3c_data = uni3c_data, latent_model_input_ovi=latent_model_input_ovi, flashvsr_LQ_latent=flashvsr_LQ_latent,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/ia/images/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes_sampler.py", line 1652, in predict_with_cfg
    raise e
  File "/opt/ia/images/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes_sampler.py", line 1522, in predict_with_cfg
    noise_pred_cond, noise_pred_ovi, cache_state_cond = transformer(
                                                        ~~~~~~~~~~~^
        context=positive_embeds,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        **base_params
        ^^^^^^^^^^^^^
    )
    ^
  File "/opt/ia/images/ComfyUI/venv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/ia/images/ComfyUI/venv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/ia/images/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 3125, in forward
    x = self.head(x, e.to(x.device), temp_length=F,
                  e_tr=e_token_replace.to(x.device) if use_token_replace else None, tr_start=token_replace_start, tr_num=replace_token_num)
  File "/opt/ia/images/ComfyUI/venv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/ia/images/ComfyUI/venv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: Head_adaLN.forward() got an unexpected keyword argument 'e_tr'

Prompt executed in 32.16 seconds


```

**Comment by kijai** [comment]
> Hello all, same here: my cat is very sad. 
> Still have the issue.
> 
> Workflow: 
> [LongCat_v03.json](https://github.com/user-attachments/files/24103604/LongCat_v03.json)
> 
> ERROR:
> 
> 
> ```
> 
> got prompt
> WARNING: [Errno 2] No such file or directory: '/opt/ia/images/ComfyUI/input/00018-_3704846037_DPM++ 2M.png'
> Using accelerate to load and assign model weights to device...
> Loading transformer parameters to cuda:0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1310/1310 [00:02<00:00, 541.80it/s]
> Using 480 LoRA weight patches for WanVideo model
> ------- Scheduler info -------
> Total timesteps: tensor([1000.0000,  992.8058,  984.3750,  974.3589,  962.2642,  947.3684,  923.0769,  896.7972,  860.7595,  808.2901,  724.8322,  571.4286], device='cuda:0')
> Using timesteps: tensor([1000.0000,  992.8058,  984.3750,  974.3589,  962.2642,  947.3684,  923.0769,  896.7972,  860.7595,  808.2901,  724.8322,  571.4286], device='cuda:0')
> Using sigmas: tensor([1.0000, 0.9928, 0.9844, 0.9744, 0.9623, 0.9474, 0.9231, 0.8968, 0.8608, 0.8083, 0.7248, 0.5714, 0.0000], device='cuda:0')
> ------------------------------
> sigmas: tensor([1.0000, 0.9928, 0.9844, 0.9744, 0.9623, 0.9474, 0.9231, 0.8968, 0.8608, 0.8083, 0.7248, 0.5714, 0.0000], device='cuda:0')
> Input sequence length: 37440
> Sampling 93 frames at 832x480 with 12 steps
>   0%|                                                                                                                                                                                      | 0/12 [00:00<?, ?it/s]Error during model prediction: Head_adaLN.forward() got an unexpected keyword argument 'e_tr'
>   0%|                                                                                                                                                                                      | 0/12 [00:27<?, ?it/s]
> Error during sampling: Head_adaLN.forward() got an unexpected keyword argument 'e_tr'
> !!! Exception during processing !!! Head_adaLN.forward() got an unexpected keyword argument 'e_tr'
> Traceback (most recent call last):
>   File "/opt/ia/images/ComfyUI/execution.py", line 515, in execute
>     output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
>                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/ia/images/ComfyUI/execution.py", line 329, in get_output_data
>     return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/ia/images/ComfyUI/execution.py", line 303, in _async_map_node_over_list
>     await process_inputs(input_dict, i)
>   File "/opt/ia/images/ComfyUI/execution.py", line 291, in process_inputs
>     result = f(**inputs)
>   File "/opt/ia/images/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes_sampler.py", line 3178, in process
>     raise e
>   File "/opt/ia/images/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes_sampler.py", line 3042, in process
>     noise_pred, noise_pred_ovi, self.cache_state = predict_with_cfg(
>                                                    ~~~~~~~~~~~~~~~~^
>         latent_model_input,
>         ^^^^^^^^^^^^^^^^^^^
>     ...<4 lines>...
>         wananim_face_pixels=wananim_face_pixels, wananim_pose_latents=wananim_pose_latents, uni3c_data = uni3c_data, latent_model_input_ovi=latent_model_input_ovi, flashvsr_LQ_latent=flashvsr_LQ_latent,
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     )
>     ^
>   File "/opt/ia/images/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes_sampler.py", line 1652, in predict_with_cfg
>     raise e
>   File "/opt/ia/images/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes_sampler.py", line 1522, in predict_with_cfg
>     noise_pred_cond, noise_pred_ovi, cache_state_cond = transformer(
>                                                         ~~~~~~~~~~~^
>         context=positive_embeds,
>         ^^^^^^^^^^^^^^^^^^^^^^^^
>     ...<2 lines>...
>         **base_params
>         ^^^^^^^^^^^^^
>     )
>     ^
>   File "/opt/ia/images/ComfyUI/venv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
>   File "/opt/ia/images/ComfyUI/venv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/opt/ia/images/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 3125, in forward
>     x = self.head(x, e.to(x.device), temp_length=F,
>                   e_tr=e_token_replace.to(x.device) if use_token_replace else None, tr_start=token_replace_start, tr_num=replace_token_num)
>   File "/opt/ia/images/ComfyUI/venv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
>   File "/opt/ia/images/ComfyUI/venv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
>     return forward_call(*args, **kwargs)
> TypeError: Head_adaLN.forward() got an unexpected keyword argument 'e_tr'
> 
> Prompt executed in 32.16 seconds
> 
> 
> ```
> 

Your nodes just aren't updated, need to be on nightly version currently which includes the fix for that.
